### ISSUE TITLE
Namron Zigbee Wallcontroller 4-channel 8-button white (4512703)

### ISSUE THREAD

**Issue by HelaContado** [easyhomesrc/Homey_Issues#9]
Adding the wallcontroller in the app seems succesful, but when trying to use the controller in a flow the scenes "list" is empty. Therefore it is not possible to choose a button to start a flow. Waking the controller works and gives battery information (100%).

Tried removing the controller and adding again. Also tried restarting homey and take battery in and out of controller.

Manufacturer ID: Namron AS
Product ID: 4512703
Device ID: 1
Profile ID: 260

Is it possible to add support for this device?

I enjoy the easyhome app, thanks in advance!

**Comment by jarll** [comment]
Same result here: Scene list is empty. Suspected my non-English language to be the cause, but changing to English on the Home device made no difference.
Not sure what values to use as "button"/"scene" values to match with, so unable to test/make that work too.
PS! Pairing is unstable and requires quite a few attempts. Can't make pairing Easyhome->WallController work, but pairing Homey->Zigbee works most times.

**Comment by HelaContado** [comment]
Seems like we have more or less the same negative experience then  @jarll ! My wallcontroller pairs every time I try, both with EasyHome and general zigbee under Homey, but it takes much longer time than anything else that I’ve paired with Homey before. I reset the wallcontroller between every attempt. Scenes list is always empty..

**Comment by jarll** [comment]
I exchanged my Zigbee device with the equivalent Z-wave version of the wallcontroller. That one pairs with Homey within seconds and immediately gave me access to the list of available scenes from the Flow designer.

**Comment by easyhomesrc** [comment]
Hi, @HelaContado 

Does EasyHome (v1.0.22) support `4512703` now?

Actually we also encountered the problem that ZigBee device is difficult to match.  We fixed this problem by restarting the Homey Gateway and resetting ZigBee in the Home App. I suggest to upgrade the firmware version of Homey Gateway to the latest version.

**Comment by easyhomesrc** [comment]
Hi, @jarll 

Thanks for your valuable feedback, we'll compare the ZigBee device and the Z-Wave device and update the EasyHome App.

**Comment by HelaContado** [comment]
Hi @easyhomesrc 
Unfortunately it still does not work. Scenes list is still empty after adding the wallcontroller (which takes an abnormally long time). Homey is the newest firmware. Also tried rebooting homey. It doesn’t work so far.

**Comment by easyhomesrc** [comment]
Hi @HelaContado 

I have added Flow support for the device, you can test in advance:
https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

App has been published and is awaiting review.

**Comment by HelaContado** [comment]
@easyhomesrc how nice! I’m looking forward to test it. Will give feedback as soon as I have tested it. Thanks in advance.

**Comment by HelaContado** [comment]
Hi @easyhomesrc 
I just couldn’t wait. So I had to test the new app right away. First, thank you so much!

The controller now works with the easyhome app, but... channel two doesn’t work at all. The other channels work just perfect. I’ve included a couple of screenshots. My homey is in Norwegian, but I think you will understand the flows I’ve made just from the screenshots.
![8F07F2CB-19DC-4694-A33B-0712D087B850](https://user-images.githubusercontent.com/62765989/81486560-d7e1db00-9255-11ea-8ad7-53a693214008.png)
![45D6CD88-E508-423B-94CA-6C23A8980F8C](https://user-images.githubusercontent.com/62765989/81486561-d9130800-9255-11ea-9ec6-1c1ec28697db.png)
![21A31349-184B-4678-9A13-8C0BA828189B](https://user-images.githubusercontent.com/62765989/81486562-da443500-9255-11ea-9762-85ce5ae0f982.png)

@
![0A569E46-6FEB-4C8D-87B0-6EF4C5878013](https://user-images.githubusercontent.com/62765989/81486558-d2849080-9255-11ea-9993-d25adb164bda.png)

Channel two does not work for the following:
•channel 2 - On
•channel 2 - Off
•channel 2 - Level move up
•channel 2 - Level move down
•channel 2 - Level move stop

**Comment by HelaContado** [comment]
@easyhomesrc 
Thank you so much! 3/4 of my wallcontroller now works. 🥇

**Comment by maginawin** [comment]
@HelaContado 
I’m glad to do this. I will check this problem after weekend. 
Will the LED indicator flash when press the channel 2 buttons?

**Comment by HelaContado** [comment]
How nice of you @maginawin thanks!

Yes, LED indicator flashes green when channel two buttons are pressed.

**Comment by HelaContado** [comment]
> How nice of you @maginawin thanks!
> 
> Yes, LED indicator flashes green when channel two buttons are pressed.

All buttons channel 1 - 4 make the led indicator flash green. 👍

**Comment by easyhomesrc** [comment]
Hi, @HelaContado 

I have done many tests. The level move up/down/stop events by long press the Channel 2 buttons will be triggered, but Channel 2 buttons does't work when shot press them.

I debugged and found that I haven't received any data (events) from Homey when I shot press the Channel 2 buttons, so the code that triggers Flow cannot run. 

This may be a problem with the remote control or the Homey gateway. I'm sorry that EasyHome App cannot solve this problem. If I find the cause of the problem I will try to solve it and reply you.

**Comment by HelaContado** [comment]
Hi @easyhomesrc 
Thank you for letting me know this.

I tried to test long press on channel two again and that doesn't work for me. I tested move up, move down and move stop flows.

Most of the controller works at least, and I am very happy with that. Thank you for all support!
I hope that one day the cause of the problem is known.
Have a nice week.

**Comment by easyhomesrc** [comment]
Hi @HelaContado

I may have solved this problem. By default, Homey cannot quickly bind all groups, so I modified it, you can test in advance:
https://homey.app/en-us/app/com.easyhome.mw.zigbee/EasyHome/test/

App has been published and is awaiting review.

__Tips__: Please remove the device from Homey first, and then add it again. If it still doesn't work, delete EasyHome App from Homey and reinstall it. If it still doesn't work, you may need to restart Homey Gateway and reset Homey ZigBee of the gateway, because Homey will cache some error information.

If it is difficult to add a remote control, timeout is often prompted, please short press the remote control every 10 seconds to activate it when Homey App shows "Please wait ...", because Homey is synchronizing data with the remote control, but the remote control will automatically sleep. If the data synchronizing is not completed, the adding will fail.

**Comment by HelaContado** [comment]
Thank you @easyhomesrc !
The wallcontroller works perfect in version 1.0.27. All buttons / functions works.

Thanks a lot

**Comment by easyhomesrc** [comment]
Hi, @HelaContado 
^_^ I'm glad to hear this news. If you have problems in the future, contact me again here.

Regards,
Wang
